sudo: required
language: php
dist: trusty

addons:
  chrome: stable

php:
  - 7.1
  - 7.2

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE octolist;'

install:
  - cp .env.dusk.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - npm install
  - npm run production

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script: 
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success: 
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false